name: "Bug report"
description: "Something is broken or regressed"
title: "fix: "
labels: ["type:bug", "triage"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      value: |
        1. ...
        2. ...
  - type: input
    id: env
    attributes:
      label: Environment (OS/Browser/Device)
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
